"""Agent 包：M3 大脑侧的 VLM 客户端、配置与最小工具循环。spec §10.1 M3-A/M3-B。

- ``QwenVLM``：OpenAI 兼容 chat/completions + 原生 tool-calling（DashScope
  qwen3.7-plus 配方），transport 可注入（测试零网络）
- ``AgentConfig``：VLM + bridge + 循环聚合配置；local.md ```env 围栏块或环境
  变量装载，key 只存在于 gitignored 文件，绝不入库
- ``AgentLoop``（M3-B）：最小整机大脑循环——玩家聊天指令 → 感知 → VLM 决策 →
  工具执行 → 游戏内回话；``ToolRegistry``/``default_registry`` 组装 function-calling
  工具表（M3 白名单最小集 + 可扩展）
"""

from .config import (
    LoopConfig,
    VLMConfig,
    AgentConfig,
    VLM_ENV_PREFIX,
    parse_env_fenced_block,
)
from .loop import (
    DEFAULT_ECHO_WINDOW,
    END_PREEMPT,
    NIL_UUID,
    PARTIAL_DONE_PREFIX,
    REFLEX_NOTICE_PREFIX,
    STATUS_PREFIX,
    STOP_REPLY_TEXT,
    STOP_WORDS,
    URGENT_PREFIX,
    AgentLoop,
    LoopClient,
    SelfEchoFilter,
    TaskRun,
    ToolExec,
    bridge_error_hint,
    match_self_uuid,
)
from .primitives import Primitives
from .reflexes import (
    LEVEL_LABELS,
    LEVEL_SWITCH_WORDS,
    REFLEX_LEVEL_PREFIX,
    BodyState,
    ReflexChain,
    ReflexLevel,
    ReflexScheduler,
    ThreatFact,
    instincts_section,
    match_reflex_level_command,
    parse_reflex_level,
)
from .tools import (
    BRIDGE_WHITELIST,
    COLLECT_BLOCK_TOOL,
    COMMAND_TOOL,
    DIG_BLOCK_TOOL,
    FINISH_TOOL,
    PICKUP_TOOL,
    WALK_TO_TOOL,
    CollectBlockParams,
    DigBlockParams,
    PickupParams,
    ToolOutcome,
    ToolRegistry,
    ToolSpec,
    UnknownToolError,
    WalkToParams,
    compact_json,
    default_registry,
    load_schema_parameters,
)
from .vlm import (
    CODE_INVALID_RESPONSE,
    CODE_NETWORK_ERROR,
    QwenVLM,
    ToolCall,
    VLMError,
    VLMResponse,
    VLMUsage,
    VLMAuthError,
    sniff_image_mime,
    system_message,
    to_data_url,
    tool_result_message,
    urllib_transport,
    user_message,
)

__all__ = [
    "AgentConfig",
    "AgentLoop",
    "BRIDGE_WHITELIST",
    "BodyState",
    "COLLECT_BLOCK_TOOL",
    "COMMAND_TOOL",
    "DEFAULT_ECHO_WINDOW",
    "DIG_BLOCK_TOOL",
    "END_PREEMPT",
    "FINISH_TOOL",
    "LEVEL_LABELS",
    "LEVEL_SWITCH_WORDS",
    "LoopClient",
    "LoopConfig",
    "NIL_UUID",
    "PARTIAL_DONE_PREFIX",
    "PICKUP_TOOL",
    "Primitives",
    "QwenVLM",
    "REFLEX_LEVEL_PREFIX",
    "REFLEX_NOTICE_PREFIX",
    "ReflexChain",
    "ReflexLevel",
    "ReflexScheduler",
    "SelfEchoFilter",
    "STATUS_PREFIX",
    "STOP_REPLY_TEXT",
    "STOP_WORDS",
    "TaskRun",
    "ThreatFact",
    "ToolCall",
    "ToolExec",
    "ToolOutcome",
    "ToolRegistry",
    "ToolSpec",
    "UnknownToolError",
    "URGENT_PREFIX",
    "VLMConfig",
    "VLMError",
    "VLMResponse",
    "VLMUsage",
    "VLMAuthError",
    "VLM_ENV_PREFIX",
    "WALK_TO_TOOL",
    "CODE_NETWORK_ERROR",
    "CODE_INVALID_RESPONSE",
    "CollectBlockParams",
    "DigBlockParams",
    "PickupParams",
    "WalkToParams",
    "bridge_error_hint",
    "compact_json",
    "default_registry",
    "instincts_section",
    "load_schema_parameters",
    "match_reflex_level_command",
    "match_self_uuid",
    "parse_env_fenced_block",
    "parse_reflex_level",
    "sniff_image_mime",
    "system_message",
    "to_data_url",
    "tool_result_message",
    "urllib_transport",
    "user_message",
]
